### ISSUE TITLE
only for info: PHP can not handle multibyte strings

### ISSUE THREAD

**Issue by voku** [Josantonius/PHP-Str#1]
e.g.: UTF8::str_starts_with('ΚόσμεMiddleEnd', 'Κόσμε'); // true

doc: https://github.com/voku/portable-utf8#str_starts_withstring-haystack-string-needle--bool
code: https://github.com/voku/portable-utf8/blob/master/src/voku/helper/UTF8.php#L4886

**Comment by Josantonius** [comment]
Thanks for the tip, Voku. Good library!

In principle, in these two methods where it is only validated if the string exists, it shouldn't be a problem:

```
Str::startsWith('Κόσμε', 'ΚόσμεMiddleΚόσμε'); //true
Str::endsWith('Κόσμε', 'ΚόσμεMiddleΚόσμε');  //true
```

**Comment by voku** [comment]
correct, it calculates the wrong string- / byte-lengths for both values and so the result for this methods are still correct :-)
